function rot13(str) {
    // Create an empty string variable so that the function can add values to it later on 
    // when the code is deciphered.
    var solved = ""

    // Create a for loop that loops through the string argument. Within the for loop, 
    // create a variable that converts the value of the string into an ASCII value.
    for (var i = 0; i < str.length; i++) {
        var asciiNum = str[i].charCodeAt();

    // Create an if statement within the for loop. If asciiNum is greater than or 
    // equal to 65 AND less than or equal to 77, a string from the char code 
    // (generated by adding 13 to the ASCII number) will be added to the empty 'solved' string.
        if (asciiNum >= 65 && asciiNum <= 77) {
            solved += String.fromCharCode(asciiNum + 13);
    // Create an else if statement that takes 13 away from the asciiNum before adding 
    // to the empty 'solved' string, when the asciiNum is greater than / equal to 78 AND 
    // less than / equal to 90.
        } else if (asciiNum >= 78 && asciiNum <= 90) {
            solved += String.fromCharCode(asciiNum - 13);
    // Create an else statement that passes on non-alphabetic characters 
    // (such as spaces and hyphens) by adding str[i] to the 'solved' string.
        } else {
            solved += str[i];
        }
    }
    return solved;
}

console.log(rot13("GUR DHVPX OEBJA SBK WHZCF BIRE GUR YNML QBT."));